/* Exception Handling*/
#include <iostream>
using namespace std;
int main()
{
    try{
        int momsage=34;
        int sonsage=36;
        if(momsage<=sonsage){
            throw 99;
        }}
        catch(int x){
            cout<<"Error aagyaaa"<<endl;
        
    }
}